# Generated by Django 3.0.7 on 2021-01-23 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, unique=True)),
                ('quantity', models.IntegerField(default=1)),
                ('sgst', models.FloatField(default=9.0)),
                ('cgst', models.FloatField(default=9.0)),
                ('cost_price', models.FloatField(blank=True)),
                ('selling_price', models.FloatField(blank=True)),
                ('barcode', models.CharField(max_length=50, unique=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
    ]
