# Generated by Django 3.0.7 on 2021-02-08 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20210203_1041'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuperMarket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='stock',
            name='super_market',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.SuperMarket'),
        ),
    ]
