# Generated by Django 3.0.7 on 2021-02-08 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_supermarket_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='barcode',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='stock',
            name='name',
            field=models.CharField(max_length=254),
        ),
    ]
