# Generated by Django 3.0.7 on 2021-02-17 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_auto_20210208_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='supplier_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='supermarket',
            name='gstno',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together={('barcode', 'super_market', 'supplier_name')},
        ),
    ]
