# Generated by Django 3.0.7 on 2021-02-19 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseitem',
            name='perprice',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='totalprice',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='perprice',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='totalprice',
            field=models.FloatField(default=1.0),
        ),
    ]
