# Generated by Django 3.0.7 on 2021-03-02 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_auto_20210217_0601'),
        ('transactions', '0002_auto_20210219_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseitem',
            name='perprice',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='totalprice',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='perprice',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='totalprice',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='EverydaySale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=100)),
                ('amount', models.FloatField(default=0.0)),
                ('date', models.DateField(auto_now_add=True)),
                ('super_market', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.SuperMarket')),
            ],
        ),
    ]
