# Generated by Django 3.0.7 on 2021-03-03 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_auto_20210303_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseitem',
            name='perprice',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='quantity',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='totalprice',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='perprice',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='quantity',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='totalprice',
            field=models.FloatField(default=1),
        ),
    ]
