# Generated by Django 3.0.7 on 2021-03-04 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_auto_20210217_0601'),
        ('transactions', '0005_auto_20210303_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='everydaysale',
            name='date',
            field=models.DateField(),
        ),
        # migrations.AlterUniqueTogether(
        #     name='everydaysale',
        #     unique_together={('date', 'super_market')},
        # ),
    ]
