# Generated by Django 3.0.7 on 2021-03-04 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_auto_20210304_1109'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='everydaysale',
            unique_together=set(),
        ),
    ]
